export const API_ENDPOINTS = {
  AUTH: {
    REQUEST_OTP: "/auth/request-otp",
    VERIFY_OTP: "/auth/verify-otp",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    LOGOUT_ALL: "/auth/logout-all",
    SESSIONS: "/auth/sessions",
  },
  USERS: {
    ME: "/me",
  },
  CATEGORIES: {
    LIST: "/categories",
    DETAIL: (slug: string) => `/categories/${slug}`,
    SKILLS: (categoryId: string) => `/categories/${categoryId}/skills`,
  },
  JOBS: {
    LIST: "/jobs",
    CREATE: "/jobs",
    DETAIL: (id: string) => `/jobs/${id}`,
    CANCEL: (id: string) => `/jobs/${id}/cancel`,
    START_TRAVEL: (id: string) => `/jobs/${id}/start-travel`,
    ARRIVE: (id: string) => `/jobs/${id}/arrive`,
    START: (id: string) => `/jobs/${id}/start`,
    COMPLETE: (id: string) => `/jobs/${id}/complete`,
  },
  OFFERS: {
    LIST: "/worker/offers",
    DETAIL: (id: string) => `/offers/${id}`,
    ACCEPT: (id: string) => `/offers/${id}/accept`,
    DECLINE: (id: string) => `/offers/${id}/reject`,
  },
  WORKERS: {
    NEARBY: "/workers/nearby",
    PROFILE: (id: string) => `/workers/${id}`,
    AVAILABILITY: "/workers/me/availability",
    ENROLL: "/workers/enroll",
    ME: "/workers/me",
  },
  UPLOADS: {
    PRESIGN: "/uploads/presign",
    COMPLETE: "/uploads/complete",
    DELETE: (id: string) => `/uploads/${id}`,
  },
  CONVERSATIONS: {
    LIST: "/conversations",
    FOR_JOB: (jobId: string) => `/jobs/${jobId}/conversation`,
    MARK_READ: (conversationId: string) => `/conversations/${conversationId}/read`,
  },
  MESSAGES: {
    LIST: (conversationId: string) => `/conversations/${conversationId}/messages`,
    SEND: (conversationId: string) => `/conversations/${conversationId}/messages`,
  },
  EARNINGS: {
    SUMMARY: "/earnings/summary",
    JOBS: "/earnings/jobs",
    EXPENSES: "/expenses",
    CREATE_EXPENSE: "/expenses",
    DELETE_EXPENSE: (id: string) => `/expenses/${id}`,
  },
  REVIEWS: {
    CREATE: "/reviews",
    WORKER_REVIEWS: (workerId: string) => `/reviews/workers/${workerId}`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  ADMIN: {
    STATS: "/admin/stats",
    USERS: "/admin/users",
    WORKERS: "/admin/workers",
    JOBS: "/admin/jobs",
    VERIFICATIONS: "/verification/requests",
    DISPUTES: "/admin/disputes",
    RESOLVE_DISPUTE: (id: string) => `/disputes/${id}/resolve`,
    CATEGORIES: "/admin/categories",
    AUDIT_LOGS: "/admin/audit-logs",
  },
  SPEECH: {
    TRANSCRIBE: "/speech/transcribe",
    SYNTHESIZE: "/speech/synthesize",
    DETECT_LANGUAGE: "/speech/detect-language",
    STATUS: "/speech/status",
  },
  AI: {
    CLASSIFY_JOB: "/ai/classify-job",
    EXTRACT_PROFILE: "/ai/extract-profile",
    SIMPLIFY_DESCRIPTION: "/ai/simplify-description",
    TRANSLATE: "/ai/translate",
    STATUS: "/ai/status",
  },
} as const;
