export const API_ENDPOINTS = {
  AUTH: {
    REQUEST_OTP: "/auth/request-otp",
    VERIFY_OTP: "/auth/verify-otp",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    LOGOUT_ALL: "/auth/logout-all",
    SESSIONS: "/auth/sessions",
  },
  USERS: {
    ME: "/me",
    UPDATE_PROFILE: "/users/profile",
  },
  CATEGORIES: {
    LIST: "/categories",
    DETAIL: (slug: string) => `/categories/${slug}`,
  },
  JOBS: {
    LIST: "/jobs",
    CREATE: "/jobs",
    DETAIL: (id: string) => `/jobs/${id}`,
    MATCHING: (id: string) => `/jobs/${id}/matching`,
    OFFERS: (jobId: string) => `/jobs/${jobId}/offers`,
    STATUS: (id: string) => `/jobs/${id}/status`,
    CANCEL: (id: string) => `/jobs/${id}/cancel`,
    ACCEPT: (id: string) => `/jobs/${id}/accept`,
    START_TRAVEL: (id: string) => `/jobs/${id}/start-travel`,
    ARRIVE: (id: string) => `/jobs/${id}/arrive`,
    START_WORK: (id: string) => `/jobs/${id}/start-work`,
    COMPLETE: (id: string) => `/jobs/${id}/complete`,
    VERIFY_OTP: (id: string) => `/jobs/${id}/verify-otp`,
  },
  OFFERS: {
    LIST: "/worker/offers",
    DETAIL: (id: string) => `/worker/offers/${id}`,
    ACCEPT: (id: string) => `/worker/offers/${id}/accept`,
    DECLINE: (id: string) => `/worker/offers/${id}/decline`,
  },
  WORKERS: {
    NEARBY: "/workers/nearby",
    PROFILE: (id: string) => `/workers/${id}`,
    AVAILABILITY: "/workers/availability",
    ONBOARDING: "/workers/onboard",
    ME: "/workers/me",
  },
  MESSAGES: {
    LIST: (jobId: string) => `/jobs/${jobId}/messages`,
    SEND: (jobId: string) => `/jobs/${jobId}/messages`,
  },
  EARNINGS: {
    SUMMARY: "/worker/earnings/summary",
    EXPENSES: "/worker/expenses",
    CREATE_EXPENSE: "/worker/expenses",
    DELETE_EXPENSE: (id: string) => `/worker/expenses/${id}`,
  },
  REVIEWS: {
    CREATE: (jobId: string) => `/jobs/${jobId}/reviews`,
    WORKER_REVIEWS: (workerId: string) => `/workers/${workerId}/reviews`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  ADMIN: {
    STATS: "/admin/stats",
    USERS: "/admin/users",
    WORKERS: "/admin/workers",
    JOBS: "/admin/jobs",
    VERIFICATIONS: "/admin/verifications",
    DISPUTES: "/admin/disputes",
    CATEGORIES: "/admin/categories",
    AUDIT_LOGS: "/admin/audit-logs",
  },
} as const;
