export const API_ENDPOINTS = {
  AUTH: {
    REQUEST_OTP: "/auth/request-otp",
    VERIFY_OTP: "/auth/verify-otp",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    LOGOUT_ALL: "/auth/logout-all",
    SESSIONS: "/auth/sessions",
  },
  USERS: {
    ME: "/me",
    UPDATE_PROFILE: "/users/profile",
  },
  CATEGORIES: {
    LIST: "/categories",
    DETAIL: (slug: string) => `/categories/${slug}`,
    SKILLS: (categoryId: string) => `/categories/${categoryId}/skills`,
  },
  JOBS: {
    LIST: "/jobs",
    CREATE: "/jobs",
    DETAIL: (id: string) => `/jobs/${id}`,
    MATCHING: (id: string) => `/jobs/${id}/matching`,
    OFFERS: (jobId: string) => `/jobs/${jobId}/offers`,
    STATUS: (id: string) => `/jobs/${id}/status`,
    CANCEL: (id: string) => `/jobs/${id}/cancel`,
    ACCEPT: (id: string) => `/jobs/${id}/accept`,
    START_TRAVEL: (id: string) => `/jobs/${id}/start-travel`,
    ARRIVE: (id: string) => `/jobs/${id}/arrive`,
    START: (id: string) => `/jobs/${id}/start`,
    COMPLETE: (id: string) => `/jobs/${id}/complete`,
  },
  OFFERS: {
    LIST: "/worker/offers",
    DETAIL: (id: string) => `/offers/${id}`,
    ACCEPT: (id: string) => `/offers/${id}/accept`,
    DECLINE: (id: string) => `/offers/${id}/reject`,
  },
  WORKERS: {
    NEARBY: "/workers/nearby",
    PROFILE: (id: string) => `/workers/${id}`,
    AVAILABILITY: "/workers/me/availability",
    ENROLL: "/workers/enroll",
    ME: "/workers/me",
  },
  UPLOADS: {
    PRESIGN: "/uploads/presign",
    COMPLETE: "/uploads/complete",
    DELETE: (id: string) => `/uploads/${id}`,
  },
  MESSAGES: {
    LIST: (conversationId: string) => `/conversations/${conversationId}/messages`,
    SEND: (conversationId: string) => `/conversations/${conversationId}/messages`,
  },
  EARNINGS: {
    SUMMARY: "/earnings/summary",
    EXPENSES: "/expenses",
    CREATE_EXPENSE: "/expenses",
    DELETE_EXPENSE: (id: string) => `/expenses/${id}`,
  },
  REVIEWS: {
    CREATE: "/reviews",
    WORKER_REVIEWS: (workerId: string) => `/reviews/workers/${workerId}`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  ADMIN: {
    STATS: "/admin/stats",
    USERS: "/admin/users",
    WORKERS: "/admin/workers",
    JOBS: "/admin/jobs",
    VERIFICATIONS: "/verification/requests",
    DISPUTES: "/admin/disputes",
    RESOLVE_DISPUTE: (id: string) => `/disputes/${id}/resolve`,
    CATEGORIES: "/admin/categories",
    AUDIT_LOGS: "/admin/audit-logs",
  },
} as const;
